before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
language: java
script:
  - java -version
  - javac -version
  - javac -cp ./src:./bin:./tools/junit.jar -d ./bin ./src/Model/*.java ./test/Model/*.java
  - java -cp ./bin:../junit.jar:./bin/model Model.FormuleTest
