before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
language: java
script:
  - java -version
  - javac -version
  - python asciidoc-8.6.7/asciidoc.py --version
  - javac -cp ./src:./bin:./tools/junit.jar -d ./bin ./src/model/*.java ./test/model/*.java
  - java -cp ./bin:../junit.jar:./bin/model model.FormuleTest
